[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#009688"
backgroundColor = "#F0F0F0"
secondaryBackgroundColor = "#E0E0E0"
textColor = "#000000"

[client]
menuItems.pagesOrder = "pages.toml"
